// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function normalizePostgresSslMode(value?: string) {
	if (!value) {
		return value;
	}

	try {
		const url = new URL(value);
		const sslMode = url.searchParams.get("sslmode");

		if (sslMode && ["prefer", "require", "verify-ca"].includes(sslMode)) {
			url.searchParams.set("sslmode", "verify-full");
		}

		return url.toString();
	} catch {
		return value;
	}
}

export default defineConfig({
	schema: "prisma/schema.prisma",
	migrations: {
		path: "prisma/migrations",
	},
	datasource: {
		url: normalizePostgresSslMode(process.env["DATABASE_URL"]),
	},
});
